title: Just the Repo
description: Test repo using Just-the-Docs process
baseurl: "/justtherepo" # your repository name
url: "https://yourusername.github.io" # your GitHub Pages URL

color_scheme: light

# Enable search
search_enabled: true

# Navigation links
aux_links:
  "View on GitHub":
    - "//github.com/yourusername/my-documentation"