title: Just the Repo
description: Test repo using Just-the-Docs process
theme: just-the-docs

baseurl: "/justtherepo"
url: "https://yourusername.github.io"

color_scheme: dark

# Enable search
search_enabled: true

# Navigation links
aux_links:
  "View on GitHub":
    - "//github.com/yourusername/my-documentation"